### ISSUE TITLE
EXTERNAL-IP pending indefinitely

### ISSUE THREAD

**Issue by dlouwers** [MicrosoftDocs/azure-docs.nl-nl#154]
After following this guide I have the following service defined:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: service-name
spec:
  loadBalancerIP: &lt;my_public_ip&gt;
  type: LoadBalancer
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: my-application
```

I have replaced names and IP. The IP is a statically assigned IPv4 in the same resourcegroup as the node. When running `kubectl get services` the external IP of the service remains pending indefinitely.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 7179d4ae-db6e-7f7c-a855-db0e0475dae9
* Version Independent ID: 1a6fa0e8-e175-ae4d-a9d6-d170255a598e
* Content: [Gebruik een statisch IP-adres aan de load balancer van Azure Kubernetes Service (AKS)](https://docs.microsoft.com/nl-nl/azure/aks/static-ip)
* Content Source: [articles/aks/static-ip.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/aks/static-ip.md)
* Service: **container-service**
* GitHub Login: @iainfoulds
* Microsoft Alias: **iainfou**
