### ISSUE TITLE
ca_version still in template

### ISSUE THREAD

**Issue by WebSpider** [MicrosoftDocs/azure-docs.nl-nl#80]
The Deployment.spec.template.spec.containers.image still contains the ca_version variable. This should be replaced by the acual value of cluster-autoscaler that you guys want to support..

There is a piece of text that somewhat gives the user instructions on the choice here, but that could be enhanced, as well as the instructions to actually replace ca_version, to a line such as this:

```yaml
    spec:
      serviceAccountName: cluster-autoscaler
      containers:
      - image: k8s.gcr.io/cluster-autoscaler:1.2.2
        imagePullPolicy: Always
        name: cluster-autoscaler
```

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 301b44e3-4be7-6364-01b4-c2a55ff9b14a
* Version Independent ID: 62569967-65c6-ece6-2d1e-689a73dd59ca
* Content: [Kubernetes op Azure - Cluster automatisch schalen](https://docs.microsoft.com/nl-nl/azure/aks/autoscaler)
* Content Source: [articles/aks/autoscaler.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/aks/autoscaler.md)
* Service: **container-service**
* GitHub Login: @sakthivetrivel
* Microsoft Alias: **sakthivetrivel**
